### ISSUE TITLE
Bad stack trace for error

### ISSUE THREAD

**Issue by anorsich** [auxilincom/node-mongo#7]
With node-mongo we usually get not very helpful stack trace, like this one: 

``` 
 level:  "error"   
  message:  "MongoServiceError: Document not found while updating. Query: {"_id":"5cc4a6f9361f3f0012151b4c"}
    at MongoService.update (/app/node_modules/@auxilin/node-mongo/src/MongoService.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)"   
  timestamp:  "2019-04-29T06:38:49.924Z"   
```

How do we improve it to show where this error has happened?

**Comment by ezhivitsa** [comment]
@anorsich As far as I understand the problem has appeared because Node.js can't capture stack trace inside an asynchronous function. But in Node 12 there is a flag `--async-stack-traces` in order to resolve the problem. But this flag should be used in the application itself.

**Comment by anorsich** [comment]
We'll have to wait until `2019-10-22` for Node 12 to become LTS release, but this is certainly better than nothing :) @ezhivitsa
